server:
  port: 8101

spring:
  application:
    name: bear-auth
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  jackson:
    default-property-inclusion: non_empty
    #    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail_on_unknown_properties: false
    mapper:
      use_getters_as_setters: false
    parser:
      allow_single_quotes: false
      allow_unquoted_control_chars: true
    serialization:
      fail_on_empty_beans: false

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://bear:123456@localhost:8001/register/eureka/
